# Generated by Django 5.1.5 on 2025-01-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
